---
name: tagged-release

on:
  push:
    tags:
      - "*"

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install 1.86.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.86.0
          override: true
          components: rustfmt, clippy

  gh_tagged_release:
    runs-on: "ubuntu-latest"
    needs: "check"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4.2.2"
        with:
          lfs: true
          fetch-depth: 0

      - name: apt update
        run: sudo apt-get update

      - name: Install libdbus
        run: sudo apt-get install libdbus-1-dev

      - name: "Cache rust binaries"
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: "cargo build --release --bin dbusevents"
      - run: "cargo build --release --bin dbusbtinfo"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "${{ github.event.release.tag_name }}"
          files: |
            target/release/dbusevents
            target/release/dbusbtinfo

        id: "automatic_releases"